version: 2.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.11-stretch
    working_directory: ~/orion-server
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    steps:
    - checkout
    - run: sudo apt update && sudo apt install -y librdkafka-dev
    - run: go mod download
    - save_cache:
        key: orion-server-{{ arch }}-{{ .Branch }}
        paths:
          - ./vendor
        when: on_success
    - run: go build -tags static -v -a -installsuffix cgo
    - persist_to_workspace:
        root: ~/orion-server
        paths:
          - orion-server
          - Dockerfile
          - default.toml
  push-image:
    docker:
    - image: circleci/golang:1.11-stretch
    working_directory: ~/orion-server
    steps:
    - setup_remote_docker
    - attach_workspace:
        at: ~/orion-server
    - run: |
        docker build -t thapovan/orion-server:latest .
        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
        docker push thapovan/orion-server:latest
        rm ~/.docker/config.json
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - push-image:
          requires:
            - build